import { Project, Task, Team, Analytics, User } from "@/types";

export const mockUser: User = {
  id: "1",
  email: "john.doe@example.com",
  name: "John Doe",
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&h=32&fit=crop&crop=face",
  role: "admin",
  createdAt: new Date("2023-01-15"),
  lastActiveAt: new Date(),
};

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "E-commerce Platform",
    description: "Modern e-commerce platform with advanced features",
    status: "active",
    priority: "high",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-06-30"),
    createdAt: new Date("2023-12-15"),
    updatedAt: new Date(),
    ownerId: "1",
    teamId: "1",
    progress: 75,
    tags: ["frontend", "backend", "e-commerce"],
  },
  {
    id: "2",
    name: "Mobile App Redesign",
    description: "Complete redesign of the mobile application",
    status: "planning",
    priority: "medium",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-05-15"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date(),
    ownerId: "1",
    teamId: "2",
    progress: 20,
    tags: ["mobile", "design", "ux"],
  },
  {
    id: "3",
    name: "Analytics Dashboard",
    description: "Advanced analytics and reporting dashboard",
    status: "active",
    priority: "urgent",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-03-31"),
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date(),
    ownerId: "1",
    teamId: "1",
    progress: 60,
    tags: ["analytics", "dashboard", "data"],
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Implement user authentication",
    description: "Set up secure user authentication with JWT tokens",
    status: "done",
    priority: "high",
    assigneeId: "2",
    projectId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
    dueDate: new Date("2024-01-20"),
    estimatedHours: 16,
    actualHours: 18,
    tags: ["backend", "security"],
    subtasks: [
      { id: "1-1", title: "Set up JWT middleware", completed: true, createdAt: new Date("2024-01-01") },
      { id: "1-2", title: "Create login endpoint", completed: true, createdAt: new Date("2024-01-02") },
      { id: "1-3", title: "Add password hashing", completed: true, createdAt: new Date("2024-01-03") },
    ],
  },
  {
    id: "2",
    title: "Design product catalog UI",
    description: "Create modern and responsive product catalog interface",
    status: "in-progress",
    priority: "medium",
    assigneeId: "3",
    projectId: "1",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date(),
    dueDate: new Date("2024-02-15"),
    estimatedHours: 24,
    actualHours: 12,
    tags: ["frontend", "ui", "design"],
    subtasks: [
      { id: "2-1", title: "Create product grid layout", completed: true, createdAt: new Date("2024-01-10") },
      { id: "2-2", title: "Add filtering functionality", completed: false, createdAt: new Date("2024-01-12") },
      { id: "2-3", title: "Implement search feature", completed: false, createdAt: new Date("2024-01-14") },
    ],
  },
  {
    id: "3",
    title: "Set up payment integration",
    description: "Integrate Stripe payment processing",
    status: "todo",
    priority: "high",
    assigneeId: "4",
    projectId: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date(),
    dueDate: new Date("2024-02-28"),
    estimatedHours: 20,
    tags: ["backend", "payment", "integration"],
    subtasks: [],
  },
  {
    id: "4",
    title: "Create mobile wireframes",
    description: "Design wireframes for mobile app redesign",
    status: "in-progress",
    priority: "medium",
    assigneeId: "5",
    projectId: "2",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date(),
    dueDate: new Date("2024-02-10"),
    estimatedHours: 16,
    actualHours: 8,
    tags: ["design", "mobile", "wireframes"],
    subtasks: [],
  },
];

export const mockTeams: Team[] = [
  {
    id: "1",
    name: "Frontend Team",
    description: "Responsible for user interface and user experience",
    members: [
      { userId: "2", role: "manager", joinedAt: new Date("2023-06-01"), permissions: ["project:create", "task:create", "task:edit"] },
      { userId: "3", role: "member", joinedAt: new Date("2023-08-15"), permissions: ["task:create", "task:edit"] },
    ],
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Backend Team",
    description: "Handles server-side logic and database management",
    members: [
      { userId: "4", role: "manager", joinedAt: new Date("2023-05-15"), permissions: ["project:create", "task:create", "task:edit"] },
      { userId: "5", role: "member", joinedAt: new Date("2023-07-01"), permissions: ["task:create", "task:edit"] },
    ],
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date(),
  },
];

export const mockAnalytics: Analytics = {
  projectStats: {
    total: 3,
    active: 2,
    completed: 0,
    overdue: 0,
  },
  taskStats: {
    total: 4,
    completed: 1,
    inProgress: 2,
    overdue: 0,
  },
  teamStats: {
    totalMembers: 4,
    activeMembers: 4,
    productivity: 85,
  },
  timeTracking: {
    totalHours: 156,
    thisWeek: 32,
    lastWeek: 28,
    trend: "up",
  },
};

export const mockData = {
  projects: mockProjects,
  tasks: mockTasks,
  teams: mockTeams,
  analytics: mockAnalytics,
};
